# Continuous Delivery Workflow
#
# This should happen whenever we push a new tag, and we tag an existing
# commit after we know it's good (e.g., has been tested).
#
# To create a new tag, we also need to update the package.json version:
#
# $ npm version 0.5.0
#
# This will update `version` in package.json to `0.5.0` and create a new
# tag, `v0.5.0` in git. We'll then use this tag (i.e., `v0.5.0`) to tag
# our docker image before we push to AWS.
name: cd

on:
  push:
    # Whenever a new tag is pushed
    tags:
      # Any tag starting with v... should trigger this workflow.
      - 'v**'

jobs:
  # NOTE: this assumes our CI jobs have already passed previously
  # (i.e., that we don't tag a commit manually until we know a build is working)
  aws:
    name: AWS
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install node dependencies
        run: npm ci

      - name: Build integration-test containers
        run: docker compose up --build -d

      - name: Setup local AWS resources
        run: ./scripts/local-aws-setup.sh

      - name: Run Hurl integration tests
        run: npm run test:integration

      - name: Stop integration-test containers
        if: always()
        run: docker compose down

      # Use buildx, which is faster and can optimize the build steps
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Configure AWS Credentials using Secrets
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Use our GitHub Encrypted Secrets via secrets.*
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # Hard-code our region, which isn't a secret, and won't change
          aws-region: us-east-2

      # Login to our ECR repository using the configured credentials
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build and Push an Image to Amazon ECR
      - name: Build and push to Amazon ECR
        env:
          # Define an Environment Variable with our ECR Registry, getting
          # the value from the previous step's outputs
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          # Define an Environment Variable with our ECR Repository Name
          ECR_REPO: fragments
          # We'll give this image two different tags. First, we'll use the git tag (vX.Y.Z)
          # so that we can always go back and re-create this setup again in the future
          # if we have to test or debug something. Second, we'll also replace the
          # `latest` tag, since this is our most up-to-date version.
          VERSION_TAG: ${{ github.ref_name }}
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          # ECS Fargate is configured to run Linux/X86_64 tasks.
          platforms: linux/amd64
          # Use the git tag version and `latest`
          tags: |
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO }}:${{ env.VERSION_TAG }}
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Update the exported task definition to use the image built for this tag.
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: update-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPO: fragments
          VERSION_TAG: ${{ github.ref_name }}
        with:
          task-definition: fragments-definition.json
          container-name: fragments-container
          image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO }}:${{ env.VERSION_TAG }}
          environment-variables: |
            PORT=80
            NODE_ENV=production
            FRAGMENTS_LOG_LEVEL=info
            API_URL=http://fragments-lb-2137875786.us-east-2.elb.amazonaws.com
            AWS_REGION=us-east-2
            AWS_COGNITO_POOL_ID=us-east-2_WT4l7j6z1
            AWS_COGNITO_CLIENT_ID=6u7uqrmeibpriuv53pboj2b38r
            AWS_S3_BUCKET_NAME=mikedohyunlim-fragments-ccp555
            AWS_DYNAMODB_TABLE_NAME=fragments

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.update-task-def.outputs.task-definition }}
          cluster: fragments-cluster
          service: fragments-task
          wait-for-service-stability: true
